- name: configure backend server
  hosts: web
  become: yes
  vars:

  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable node js -y

  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable node js:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: installed

  - name: create user expense
    ansible.builtin.user:
      name: expense

  - name: create app directory
    ansible.builtin.file:
       path: /app
       state: directory

  - name: download backened code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip