- name: configure db server
  hosts: db
  become: yes
  tasks:
  - name: Install mysql server
    ansible.builtin.dnf:
     name: mysql-server
     state: latest

  - name: start and enable mysql server
    ansible.builtin.service:
     name: mysqld
     enabled: yes

  - name: check db connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{ db.daws-78s.store }}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print output
    ansible.builtin.debug:
     msg: "output: {{mysql_connection_output}} "
